apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
    version: 1.0.0
spec:
  clusterIP: 10.3.244.85
  ports:
  - port: 22222
    protocol: TCP
    targetPort: 22222
  selector:
    app: accounts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}