apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-01-29T18:57:25Z
  name: accounts-service
  namespace: boiler-prod
  resourceVersion: "2286"
  selfLink: /api/v1/namespaces/boiler-prod/services/accounts-service
  uid: b796faad-23f7-11e9-b75c-42010a8000ee
spec:
  clusterIP: 10.3.244.85
  ports:
  - port: 22222
    protocol: TCP
    targetPort: 22222
  selector:
    app: accounts
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}