apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: accounts
  name: accounts
  namespace: boiler-prod
spec:
  containers:
  - image: ryanb58/boiler-accounts:latest
    name: accounts
    ports:
    - containerPort: 22222
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
  restartPolicy: OnFailure
status: {}
