apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: accounts
  name: accounts
  namespace: boiler-prod
spec:
  ports:
  - name: "22220"
    port: 22220
    targetPort: 22222
  selector:
    io.kompose.service: accounts
status:
  loadBalancer: {}
