apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  app: accounts
  version: 1.0.0
spec:
  selector:
    matchLabels:
      app: accounts
  # replicas: 3
  template:
    metadata:
      labels:
        app: accounts
        version: 1.0.0
    spec:
      containers:
      - name: accounts
        image: ryanb58/boiler-accounts:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 22222