apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  namespace: prod
  app: apigateway
  version: 1.0.0
spec:
  selector:
    matchLabels:
      app: apigateway
  # replicas: 3
  template:
    metadata:
      labels:
        namespace: prod
        app: apigateway
        version: 1.0.0
    spec:
      containers:
      - name: apigateway
        image: ryanb58/boiler-apigateway:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80