apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway
  namespace: boiler-prod
spec:
  type: loadBalancer
  ports:
  - port: 80
  selector:
    io.kompose.service: apigateway
status:
  loadBalancer: {}
