apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: contacts
  name: contacts
  name: boiler-prod
spec:
  ports:
  - name: "22221"
    port: 22221
    targetPort: 22222
  selector:
    io.kompose.service: contacts
status:
  loadBalancer: {}
