apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-01-29T18:57:46Z
  name: contacts-service
  namespace: boiler-prod
  resourceVersion: "2328"
  selfLink: /api/v1/namespaces/boiler-prod/services/contacts-service
  uid: c434f826-23f7-11e9-b75c-42010a8000ee
spec:
  clusterIP: 10.3.251.181
  ports:
  - port: 22222
    protocol: TCP
    targetPort: 22222
  selector:
    app: contacts
    tier: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
