apiVersion: v1
kind: Service
metadata:
  name: contacts
  labels:
    app: contacts
    version: 1.0.0
spec:
  ports:
  - port: 22222
    protocol: TCP
    targetPort: 22222
  selector:
    app: contacts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
