apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apigateway
spec:
  hosts:
  - "*"
  gateways:
  - boiler-gateway
  http:
  - route:
    - destination:
        host: apigateway
        subset: prod
    retries:
      attempts: 3
      perTryTimeout: 2s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: accounts
spec:
  hosts:
  - accounts
  tcp:
  - match:
    - port: 22222
    route:
    - destination:
        host: accounts
        port:
          number: 22222
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: contacts
spec:
  hosts:
  - contacts
  tcp:
  - match:
    - port: 22222
    route:
    - destination:
        host: contacts
        port:
          number: 22222